### ISSUE TITLE
sync is creating duplicate UTxO in the LOG file

### ISSUE THREAD

**Issue by HM999** [input-output-hk/cardano-byron-cli#53]
This issue puts the wallet into a bad state. Once in this bad state the wallet will report the below error for many functions:

```
./target/debug/cardano-cli wallet status my_magic_wallet
Wallet clean on blockchain mainnet
 * wallet model BIP44
 * derivation scheme V2
ERROR 2018-11-06T02:06:49Z: cardano_cli::wallet::state::state: This UTxO was already in the UTxOs collection `Ae2tdPwUPEZZZZZinWnudbNtHQddCyc6bCwLVoQx4GfH1NvwztGRpRkewTe (0.0.0) received 1.000000Ada in transaction id `60540befd34211b88888dd216410ec8772d25645ad7826e69cb20662411e8a2a.1''
thread 'main' panicked at 'The Wallet LOG file seems corrupted', src/wallet/state/state.rs:32:25
```
The bad state is that the last UTxO is stored *twice* in the LOG file. The bad state comes about by performing a second *sync* operation on the wallet. To recreate, recover a wallet that has a UTxO, sync the wallet (you can see the state is correct by doing `strings LOG` which will show the UTxO), then sync again (again `strings LOG` will show the last UTxO is now stored twice).

```
./target/debug/cardano-cli wallet sync my_magic_wallet
Enter the wallet password.
wallet password: : 
syncing wallet from 0.GENESIS to 81.13276
  [00:28:06] [########################################] 1762876/1762876 (0s)
ubuntu@ip-172-31-21-95:~/cardano-cli$ ./target/debug/cardano-cli wallet sync clean
Enter the wallet password.
wallet password: : 
syncing wallet from 81.11021 to 81.13276
  [00:00:05] [########################################] 1255/1255 (0s)
ubuntu@ip-172-31-21-95:~/cardano-cli$ ./target/debug/cardano-cli wallet status my_magic_wallet
Wallet clean on blockchain mainnet
 * wallet model BIP44
 * derivation scheme V2
ERROR 2018-11-06T02:06:49Z: cardano_cli::wallet::state::state: This UTxO was already in the UTxOs collection `Ae2tdPwUPEZZZZZinWnudbNtHQddCyc6bCwLVoQx4GfH1NvwztGRpRkewTe (0.0.0) received 1.000000Ada in transaction id `60540befd34211b88888dd216410ec8772d25645ad7826e69cb20662411e8a2a.1''
thread 'main' panicked at 'The Wallet LOG file seems corrupted', src/wallet/state/state.rs:32:25
```
It looks like the second sync, instead of starting where the last sync finished (81.13276) instead starts from the block time of the last UTxO in the log (81.11021), I am guessing this causes that UTxO to be picked up again, or maybe it is something about the reading/writing of the LOG. Not sure.

More here:
https://forum.cardano.org/t/cardano-cli/16654/19

**Comment by NicolasDP** [comment]
we have seen this issue in the passed. I think a `detatch` then `attach` again will solve the problem

**Comment by HM999** [comment]
Yes, that will solve the problem, because that will remove the LOG file, which will then be rebuilt on sync. Everything will be ok until you run sync again (which you will have to at some point) after this the wallet will be in the bad state.

I believe the quick fix is to change the file ./src/wallet/utils.rs like this:

```
    let mut blockchain_iter = blockchain.iter_to_tip(from).unwrap_or_else(|e| term.fail_with(e));
    blockchain_iter.next(); // advance by 1 block

    for res in TransactionIterator::new(progress, blockchain_iter) {
```

This makes the second sync start one block AFTER the last UTxO in the LOG file, so that UTxO will not be picked up again. Rather than currently where we start ON the block of the last UTxO.

HOWEVER, I wonder why syncs are starting from the last UTxO in the LOG file at all, shouldn't each sync record *the last block it processed* and the next sync start from the block after that one?

**Comment by chisNaN** [comment]
Hello.
I wanted to play a little with cardano-cli on both macOS and windows 10.
(I pulled the master branch approx 10 days ago)
I am commenting this issue because I managed after syncing several times a wallet
**to generate a DOUBLE UTXO CREDIT
which gives me a wrong final balance.**
Indeed if i detach and attach the wallet to the blockchain
and finally resync the wallet
last utxo credit is not duplicated in the log.
Contrarly to @HM999 I did not have any kind of fatal errors
But its quite annoying having to make the syncing operation again to be in a "correct" state.

What would you suggest?
Thanks
<img width="674" alt="duplicated-credit-cardano-cli" src="https://user-images.githubusercontent.com/2439389/54083117-f1b92280-431f-11e9-9cbf-89f727fa4023.PNG">
<img width="674" alt="status-wallet" src="https://user-images.githubusercontent.com/2439389/54083118-f251b900-431f-11e9-8995-af68f40c60d8.PNG">
<img width="674" alt="utxos" src="https://user-images.githubusercontent.com/2439389/54083119-f251b900-431f-11e9-9c13-5ed1c7ccff36.png">

**Comment by NicolasDP** [comment]
Which version are you utilising ?
